### PR TITLE
Upgrade CLI wallet to support node 20

### PR DESCRIPTION
**Pull request by NullSoldier**

### CODE REVIEW

**Review by hughy — APPROVED** [review]

**Review by patnir — COMMENTED** [review]
When I tried installing dependencies using node version 20, I got some build errors. See attached file. 
[node-20-build-errors.txt](https://github.com/iron-fish/ironfish-wallet-cli/files/13540445/node-20-build-errors.txt)

**Comment by patnir** [comment]
> When I tried installing dependencies using node version 20, I got some build errors. See attached file. [node-20-build-errors.txt](https://github.com/iron-fish/ironfish-wallet-cli/files/13540445/node-20-build-errors.txt)

Specifically with node datachannel. I know Derek ran into an issue with this too

**Comment by danield9tqh** [comment]
I think you need to upgrade `@ironfish/sdk` version to 1.13.0 in this branch to fix the `node-datachannel` errors

**Comment by NullSoldier** [comment]
Ah yes, I upgraded the SDK in this branch.

It's because I started with one branch but didn't carry over all the changes to each split out branch.

**Pull request merged**
